import Head from 'next/head'
import {getAllPosts} from "@/pages/api/getPostsList";
import {getPostDetail} from "@/pages/api/getPost/[name]";
import {useMarkdown} from "@/hooks/useMarkdown";
import Link from "next/link";


export async function getStaticProps() {
  const pages = await getAllPosts();
  const posts = pages.filter(page => page.extName.toLowerCase() === '.md' || page.extName.toLowerCase() === '.markdown')
    .map(async page => {
      const post = await getPostDetail(page.name);
      const postDetail = useMarkdown(post);
      const attr: any = postDetail.attributes;
      return {
        url: `/posts/${page.name}`,
        title: attr.title ?? '未命名',
        createTime: attr.date.toLocaleTimeString()
      }
    })

  const postsList = await Promise.all(posts);
  return {
    props: {
      posts: postsList
    }
  }
}

export default function Home({posts}: {
  posts: {
    url: string,
    title: string,
    createTime: string
  }[]
}) {

  const postList = posts.map(e => {
    return <div key={e.url} style={{margin: '1em 0 0 2em'}}>
      <Link href={e.url}>{e.title}
        <div>
          {e.createTime}
        </div>
      </Link>
    </div>
  })

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app"/>
        <meta name="viewport" content="width=device-width, initial-scale=1"/>
        <link rel="icon" href="/favicon.ico"/>
      </Head>
      <main>
        {
          postList
        }
      </main>
    </>
  )
}
